// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Belt_Int = require("rescript/lib/js/belt_Int.js");
var Solution = require("../Solution.bs.js");
var Belt_Array = require("rescript/lib/js/belt_Array.js");
var Belt_Option = require("rescript/lib/js/belt_Option.js");
var Belt_SortArrayInt = require("rescript/lib/js/belt_SortArrayInt.js");

function part01(input) {
  return input.split("\n\n").reduce((function (acc, i) {
                var rows = i.split("\n").reduce((function (acc, i) {
                        return acc + Belt_Option.getWithDefault(Belt_Int.fromString(i), 0) | 0;
                      }), 0);
                return Math.max(acc, rows);
              }), 0);
}

function sum(x) {
  return x.reduce((function (acc, i) {
                return acc + i | 0;
              }), 0);
}

function part02(input) {
  var top3 = Belt_SortArrayInt.stableSort(input.split("\n\n").map(function (i) {
            return i.split("\n").reduce((function (acc, i) {
                          return acc + Belt_Option.getWithDefault(Belt_Int.fromString(i), 0) | 0;
                        }), 0);
          }));
  return sum(Belt_Array.slice(top3, -3, 3));
}

Solution.make(part02, "day01/input");

exports.part01 = part01;
exports.sum = sum;
exports.part02 = part02;
/*  Not a pure module */
