// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Solution = require("../Solution.bs.js");
var Belt_Array = require("rescript/lib/js/belt_Array.js");
var Belt_SetString = require("rescript/lib/js/belt_SetString.js");

function cmplen(arr1, arr2) {
  return arr1.length === arr2.length;
}

function uniq(arr) {
  return cmplen(Belt_SetString.toArray(Belt_SetString.fromArray(arr)), arr);
}

function $$process(_countOpt, _characters, len) {
  while(true) {
    var countOpt = _countOpt;
    var characters = _characters;
    var count = countOpt !== undefined ? countOpt : 0;
    var isUnique = uniq(characters.slice(0, len));
    if (isUnique) {
      return len + count | 0;
    }
    _characters = Belt_Array.sliceToEnd(characters, 1);
    _countOpt = count + 1 | 0;
    continue ;
  };
}

function part01(input) {
  return $$process(undefined, input.split(""), 4);
}

function part02(input) {
  return $$process(undefined, input.split(""), 14);
}

Solution.make(part01, "day06/input");

Solution.make(part02, "day06/input");

exports.cmplen = cmplen;
exports.uniq = uniq;
exports.$$process = $$process;
exports.part01 = part01;
exports.part02 = part02;
/*  Not a pure module */
